"""add the column

Revision ID: 852f8f343955
Revises: ea1aca5f222d
Create Date: 2021-11-13 22:35:38.379291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852f8f343955'
down_revision = 'ea1aca5f222d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
